### ISSUE TITLE
'1'.pad(start); 为什么可以调用方法？（基本类型数据为什么可以调用方法？）

### ISSUE THREAD

**Issue by Mark24Code** [fe-quiz/quiz#1]
考察
1.JS的数据类型
2.拆箱、装箱
3.隐式转换
4.数据相等

**Comment by shannuo** [comment]
当基础数据类型调用方法的时候，js引擎会对它进行装箱拆箱操作，'1'.pad(start)执行过程大致就是：var strObj = new String(1); var result = strObj.pad(start) ; strObj = null; return result
