### ISSUE TITLE
new 一个对象发生了什么？手写一个new

### ISSUE THREAD

**Issue by Mark24Code** [fe-quiz/quiz#16]
1.new的过程

**Comment by Mark24Code** [comment]
new的过程

1. 创建一个空的简单JavaScript对象（即{}）；
2. 链接该对象（即设置该对象的构造函数）到另一个对象 ；
3. 将步骤1新创建的对象作为this的上下文 ；
4. 如果该函数没有返回对象，则返回this。


```javascript

function myNew() {
    // 创建一个对象
    let obj = new Object()
   // 获得构造函数
    let con = [].shift.call(arguments)
    // 链接原型
    obj.__proto__ = con.prototype
   // 绑定this，执行构造函数
    let result = con.apply(obj, arguments)
 
   // 确保new出来的是个对象
   return typeof result === 'object' ? result : obj

}

```

参考：

1.MDN:https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/new

**Comment by coolzjy** [comment]
```js
function myNew (myConstructor, ...args) {
  const obj = Object.create(myConstructor.prototype)
  const result = myConstructor.apply(obj, args)
  if (result && typeof result === 'object') return result
  return obj
}
```

**Comment by Mark24Code** [comment]
更短

```javascript
function myNew (myConstructor, ...args) {
  const obj = Object.create(myConstructor.prototype);
  const result = myConstructor.apply(obj, args);
  return typeof result === 'object' ? result : obj;
}
```

**Comment by Mark24Code** [comment]
原型相关参考：https://github.com/mqyqingfeng/Blog/issues/2

**Comment by JawilX** [comment]
> 更短
> 
> ```js
> function myNew (myConstructor, ...args) {
>   const obj = Object.create(myConstructor.prototype);
>   const result = myConstructor.apply(obj, args);
>   return typeof result === 'object' ? result : obj;
> }
> ```

你的这个如果result为null, 就返回null了, 实际上result为falsy值时都应返回obj
