### ISSUE TITLE
String（1）和 new String（1）区别

### ISSUE THREAD

**Issue by Mark24Code** [fe-quiz/quiz#2]

**Comment by shannuo** [comment]
String（1）是将1进行类型转换 转换为string类型
new String(1) 是创建了一个String对象 值为String(1)

**Comment by Mark24Code** [comment]
参考：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String#%E5%9F%BA%E6%9C%AC%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%92%8C%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%8C%BA%E5%88%AB

基本字符串 （String或者 ‘’、“”、``生成） 和 字符串对象
